In [3]:
import requests
from bs4 import BeautifulSoup
import time
import pandas as pd

Jobs_tanqeeb = []

categories = {"Data Analysis": {"query": "Data+Analysis", "pages": 296}, "Data Science": {"query": "Data+Science", "pages": 131}, "Data Engineering": {"query": "Data+Engineering", "pages": 231}, "Data Entry": {"query": "Data+Entry", "pages": 38}, "Business Intelligence": {"query": "Business+Intelligence", "pages": 108}, "Machine Learning": {"query": "Machine+Learning", "pages": 43}, "Artificial Intelligence": {"query": "Artificial+Intelligence", "pages": 30}}

headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/154.0.0.0 Safari/537.36"}

session = requests.Session()
session.headers.update(headers)

for category, info in categories.items():

    query = info["query"]
    pages = info["pages"]

    print(f"\n========== {category} | {pages} Pages ==========\n")

    for page_number in range(1, pages + 1):

        url = f"https://egypt.tanqeeb.com/jobs/search?keywords={query}&page_no={page_number}"

        try:

            response = session.get(url, timeout=30)
            response.raise_for_status()

            soup = BeautifulSoup(response.text, "html.parser")

            jobs = soup.find_all("div", class_="search-job-card")

            print(f"{category} | Page: {page_number}/{pages} | Jobs: {len(jobs)}")

            for i in jobs:

                title = i.select_one("a.search-job-title-link")
                title = title.get_text(strip=True) if title else None

                type_location = i.select_one("span.search-job-workplace-location")
                type_location = type_location.get_text(strip=True) if type_location else None

                date = i.select_one("span.search-job-date")
                date = date.get_text(strip=True) if date else None

                site_category = i.select_one("div.search-job-categories")
                site_category = site_category.get_text(strip=True) if site_category else None

                company_name = i.select_one("div.search-job-company-name")
                company_name = company_name.get_text(strip=True) if company_name else None

                type_work = i.select_one("span.search-job-tag")
                type_work = type_work.get_text(strip=True) if type_work else None

                source = i.select_one("span.search-job-source")
                source = source.get_text(strip=True) if source else None

                location_element = i.select_one("div.search-job-company-city span")
                location = location_element.get_text(strip=True) if location_element else None

                job_link = i.select_one("a.search-job-title-link")
                job_link = "https://egypt.tanqeeb.com" + job_link.get("href") if job_link and job_link.get("href") else None

                Jobs_tanqeeb.append({"Title": title, "Type_Location": type_location, "Date": date, "Category": site_category, "Data_Category": category, "Company_name": company_name, "Type_Work": type_work, "Source": source, "Location": location, "Job_Link": job_link, "Page": page_number})

            time.sleep(0.5)

        except requests.exceptions.RequestException as e:

            print(f"ERROR | {category} | Page: {page_number} | {e}")

            time.sleep(3)

            continue

df = pd.DataFrame(Jobs_tanqeeb)

print("\n====================================")
print("Scraping Finished")
print("Total Jobs:", len(df))
print("====================================")

print("\nJobs per Data Category:")
print(df["Data_Category"].value_counts())

df.head()

========== Data Analysis | 296 Pages ==========

Data Analysis | Page: 1/296 | Jobs: 20
Data Analysis | Page: 2/296 | Jobs: 20
Data Analysis | Page: 3/296 | Jobs: 20
Data Analysis | Page: 4/296 | Jobs: 20
Data Analysis | Page: 5/296 | Jobs: 20
Data Analysis | Page: 6/296 | Jobs: 20
Data Analysis | Page: 7/296 | Jobs: 20
Data Analysis | Page: 8/296 | Jobs: 20
Data Analysis | Page: 9/296 | Jobs: 20
Data Analysis | Page: 10/296 | Jobs: 20
Data Analysis | Page: 11/296 | Jobs: 20
Data Analysis | Page: 12/296 | Jobs: 20
Data Analysis | Page: 13/296 | Jobs: 20
Data Analysis | Page: 14/296 | Jobs: 20
Data Analysis | Page: 15/296 | Jobs: 20
Data Analysis | Page: 16/296 | Jobs: 20
Data Analysis | Page: 17/296 | Jobs: 20
Data Analysis | Page: 18/296 | Jobs: 20
Data Analysis | Page: 19/296 | Jobs: 20
Data Analysis | Page: 20/296 | Jobs: 20
Data Analysis | Page: 21/296 | Jobs: 20
Data Analysis | Page: 22/296 | Jobs: 20
Data Analysis | Page: 23/296 | Jobs: 20
Data Analysis | Page: 24/296 | Jobs: 20
Data Analysis | Page: 25/296 | Jobs: 20
Data Analysis | Page: 26/296 | Jobs: 20
Data Analysis | Page: 27/296 | Jobs: 20
Data Analysis | Page: 28/296 | Jobs: 20
Data Analysis | Page: 29/296 | Jobs: 20
Data Analysis | Page: 30/296 | Jobs: 20
Data Analysis | Page: 31/296 | Jobs: 20
Data Analysis | Page: 32/296 | Jobs: 20
Data Analysis | Page: 33/296 | Jobs: 20
Data Analysis | Page: 34/296 | Jobs: 20
Data Analysis | Page: 35/296 | Jobs: 20
Data Analysis | Page: 36/296 | Jobs: 20
Data Analysis | Page: 37/296 | Jobs: 20
Data Analysis | Page: 38/296 | Jobs: 20
Data Analysis | Page: 39/296 | Jobs: 20
Data Analysis | Page: 40/296 | Jobs: 20
Data Analysis | Page: 41/296 | Jobs: 20
Data Analysis | Page: 42/296 | Jobs: 20
Data Analysis | Page: 43/296 | Jobs: 20
Data Analysis | Page: 44/296 | Jobs: 20
Data Analysis | Page: 45/296 | Jobs: 20
Data Analysis | Page: 46/296 | Jobs: 20
Data Analysis | Page: 47/296 | Jobs: 20
Data Analysis | Page: 48/296 | Jobs: 20
Data Analysis | Page: 49/296 | Jobs: 20
Data Analysis | Page: 50/296 | Jobs: 20
Data Analysis | Page: 51/296 | Jobs: 20
Data Analysis | Page: 52/296 | Jobs: 20
Data Analysis | Page: 53/296 | Jobs: 20
Data Analysis | Page: 54/296 | Jobs: 20
Data Analysis | Page: 55/296 | Jobs: 20
Data Analysis | Page: 56/296 | Jobs: 20
Data Analysis | Page: 57/296 | Jobs: 20
Data Analysis | Page: 58/296 | Jobs: 20
Data Analysis | Page: 59/296 | Jobs: 20
Data Analysis | Page: 60/296 | Jobs: 20
Data Analysis | Page: 61/296 | Jobs: 20
Data Analysis | Page: 62/296 | Jobs: 20
Data Analysis | Page: 63/296 | Jobs: 20
Data Analysis | Page: 64/296 | Jobs: 20
Data Analysis | Page: 65/296 | Jobs: 20
Data Analysis | Page: 66/296 | Jobs: 20
Data Analysis | Page: 67/296 | Jobs: 20
Data Analysis | Page: 68/296 | Jobs: 20
Data Analysis | Page: 69/296 | Jobs: 20
Data Analysis | Page: 70/296 | Jobs: 20
Data Analysis | Page: 71/296 | Jobs: 20
Data Analysis | Page: 72/296 | Jobs: 20
Data Analysis | Page: 73/296 | Jobs: 20
Data Analysis | Page: 74/296 | Jobs: 20
Data Analysis | Page: 75/296 | Jobs: 20
Data Analysis | Page: 76/296 | Jobs: 20
Data Analysis | Page: 77/296 | Jobs: 20
Data Analysis | Page: 78/296 | Jobs: 20
Data Analysis | Page: 79/296 | Jobs: 20
Data Analysis | Page: 80/296 | Jobs: 20
Data Analysis | Page: 81/296 | Jobs: 20
Data Analysis | Page: 82/296 | Jobs: 20
Data Analysis | Page: 83/296 | Jobs: 20
Data Analysis | Page: 84/296 | Jobs: 20
Data Analysis | Page: 85/296 | Jobs: 20
Data Analysis | Page: 86/296 | Jobs: 20
Data Analysis | Page: 87/296 | Jobs: 20
Data Analysis | Page: 88/296 | Jobs: 20
Data Analysis | Page: 89/296 | Jobs: 20
Data Analysis | Page: 90/296 | Jobs: 20
Data Analysis | Page: 91/296 | Jobs: 20
Data Analysis | Page: 92/296 | Jobs: 20
Data Analysis | Page: 93/296 | Jobs: 20
Data Analysis | Page: 94/296 | Jobs: 20
Data Analysis | Page: 95/296 | Jobs: 20
Data Analysis | Page: 96/296 | Jobs: 20
Data Analysis | Page: 97/296 | Jobs: 20
Data Analysis | Page: 98/296 | Jobs: 20
Data Analysis | Page: 99/296 | Jobs: 20
Data Analysis | Page: 100/296 | Jobs: 20
Data Analysis | Page: 101/296 | Jobs: 20
Data Analysis | Page: 102/296 | Jobs: 20
Data Analysis | Page: 103/296 | Jobs: 20
Data Analysis | Page: 104/296 | Jobs: 20
Data Analysis | Page: 105/296 | Jobs: 20
Data Analysis | Page: 106/296 | Jobs: 20
Data Analysis | Page: 107/296 | Jobs: 20
Data Analysis | Page: 108/296 | Jobs: 20
Data Analysis | Page: 109/296 | Jobs: 20
Data Analysis | Page: 110/296 | Jobs: 20
Data Analysis | Page: 111/296 | Jobs: 20
Data Analysis | Page: 112/296 | Jobs: 20
Data Analysis | Page: 113/296 | Jobs: 20
Data Analysis | Page: 114/296 | Jobs: 20
Data Analysis | Page: 115/296 | Jobs: 20
Data Analysis | Page: 116/296 | Jobs: 20
Data Analysis | Page: 117/296 | Jobs: 20
Data Analysis | Page: 118/296 | Jobs: 20
Data Analysis | Page: 119/296 | Jobs: 20
Data Analysis | Page: 120/296 | Jobs: 20
Data Analysis | Page: 121/296 | Jobs: 20
Data Analysis | Page: 122/296 | Jobs: 20
Data Analysis | Page: 123/296 | Jobs: 20
Data Analysis | Page: 124/296 | Jobs: 20
Data Analysis | Page: 125/296 | Jobs: 20
Data Analysis | Page: 126/296 | Jobs: 20
Data Analysis | Page: 127/296 | Jobs: 20
Data Analysis | Page: 128/296 | Jobs: 20
Data Analysis | Page: 129/296 | Jobs: 20
Data Analysis | Page: 130/296 | Jobs: 20
Data Analysis | Page: 131/296 | Jobs: 20
Data Analysis | Page: 132/296 | Jobs: 20
Data Analysis | Page: 133/296 | Jobs: 20
Data Analysis | Page: 134/296 | Jobs: 20
Data Analysis | Page: 135/296 | Jobs: 20
Data Analysis | Page: 136/296 | Jobs: 20
Data Analysis | Page: 137/296 | Jobs: 20
Data Analysis | Page: 138/296 | Jobs: 20
Data Analysis | Page: 139/296 | Jobs: 20
Data Analysis | Page: 140/296 | Jobs: 20
Data Analysis | Page: 141/296 | Jobs: 20
Data Analysis | Page: 142/296 | Jobs: 20
Data Analysis | Page: 143/296 | Jobs: 20
Data Analysis | Page: 144/296 | Jobs: 20
Data Analysis | Page: 145/296 | Jobs: 20
Data Analysis | Page: 146/296 | Jobs: 20
Data Analysis | Page: 147/296 | Jobs: 20
Data Analysis | Page: 148/296 | Jobs: 20
Data Analysis | Page: 149/296 | Jobs: 20
Data Analysis | Page: 150/296 | Jobs: 20
Data Analysis | Page: 151/296 | Jobs: 20
Data Analysis | Page: 152/296 | Jobs: 20
Data Analysis | Page: 153/296 | Jobs: 20
Data Analysis | Page: 154/296 | Jobs: 20
Data Analysis | Page: 155/296 | Jobs: 20
Data Analysis | Page: 156/296 | Jobs: 20
Data Analysis | Page: 157/296 | Jobs: 20
Data Analysis | Page: 158/296 | Jobs: 20
Data Analysis | Page: 159/296 | Jobs: 20
Data Analysis | Page: 160/296 | Jobs: 20
Data Analysis | Page: 161/296 | Jobs: 20
Data Analysis | Page: 162/296 | Jobs: 20
Data Analysis | Page: 163/296 | Jobs: 20
Data Analysis | Page: 164/296 | Jobs: 20
Data Analysis | Page: 165/296 | Jobs: 20
Data Analysis | Page: 166/296 | Jobs: 20
Data Analysis | Page: 167/296 | Jobs: 20
Data Analysis | Page: 168/296 | Jobs: 20
Data Analysis | Page: 169/296 | Jobs: 20
Data Analysis | Page: 170/296 | Jobs: 20
Data Analysis | Page: 171/296 | Jobs: 20
Data Analysis | Page: 172/296 | Jobs: 20
Data Analysis | Page: 173/296 | Jobs: 20
Data Analysis | Page: 174/296 | Jobs: 20
Data Analysis | Page: 175/296 | Jobs: 20
Data Analysis | Page: 176/296 | Jobs: 20
Data Analysis | Page: 177/296 | Jobs: 20
Data Analysis | Page: 178/296 | Jobs: 20
Data Analysis | Page: 179/296 | Jobs: 20
Data Analysis | Page: 180/296 | Jobs: 20
Data Analysis | Page: 181/296 | Jobs: 20
Data Analysis | Page: 182/296 | Jobs: 20
Data Analysis | Page: 183/296 | Jobs: 20
Data Analysis | Page: 184/296 | Jobs: 20
Data Analysis | Page: 185/296 | Jobs: 20
Data Analysis | Page: 186/296 | Jobs: 20
Data Analysis | Page: 187/296 | Jobs: 20
Data Analysis | Page: 188/296 | Jobs: 20
Data Analysis | Page: 189/296 | Jobs: 20
Data Analysis | Page: 190/296 | Jobs: 20
Data Analysis | Page: 191/296 | Jobs: 20
Data Analysis | Page: 192/296 | Jobs: 20
Data Analysis | Page: 193/296 | Jobs: 20
Data Analysis | Page: 194/296 | Jobs: 20
Data Analysis | Page: 195/296 | Jobs: 20
Data Analysis | Page: 196/296 | Jobs: 20
Data Analysis | Page: 197/296 | Jobs: 20
Data Analysis | Page: 198/296 | Jobs: 20
Data Analysis | Page: 199/296 | Jobs: 20
Data Analysis | Page: 200/296 | Jobs: 20
Data Analysis | Page: 201/296 | Jobs: 20
Data Analysis | Page: 202/296 | Jobs: 20
Data Analysis | Page: 203/296 | Jobs: 20
Data Analysis | Page: 204/296 | Jobs: 20
Data Analysis | Page: 205/296 | Jobs: 20
Data Analysis | Page: 206/296 | Jobs: 20
Data Analysis | Page: 207/296 | Jobs: 20
Data Analysis | Page: 208/296 | Jobs: 20
Data Analysis | Page: 209/296 | Jobs: 20
Data Analysis | Page: 210/296 | Jobs: 20
Data Analysis | Page: 211/296 | Jobs: 20
Data Analysis | Page: 212/296 | Jobs: 20
Data Analysis | Page: 213/296 | Jobs: 20
Data Analysis | Page: 214/296 | Jobs: 20
Data Analysis | Page: 215/296 | Jobs: 20
Data Analysis | Page: 216/296 | Jobs: 20
Data Analysis | Page: 217/296 | Jobs: 20
Data Analysis | Page: 218/296 | Jobs: 20
Data Analysis | Page: 219/296 | Jobs: 20
Data Analysis | Page: 220/296 | Jobs: 20
Data Analysis | Page: 221/296 | Jobs: 20
Data Analysis | Page: 222/296 | Jobs: 20
Data Analysis | Page: 223/296 | Jobs: 20
Data Analysis | Page: 224/296 | Jobs: 20
Data Analysis | Page: 225/296 | Jobs: 20
Data Analysis | Page: 226/296 | Jobs: 20
Data Analysis | Page: 227/296 | Jobs: 20
Data Analysis | Page: 228/296 | Jobs: 20
Data Analysis | Page: 229/296 | Jobs: 20
Data Analysis | Page: 230/296 | Jobs: 20
Data Analysis | Page: 231/296 | Jobs: 20
Data Analysis | Page: 232/296 | Jobs: 20
Data Analysis | Page: 233/296 | Jobs: 20
Data Analysis | Page: 234/296 | Jobs: 20
Data Analysis | Page: 235/296 | Jobs: 20
Data Analysis | Page: 236/296 | Jobs: 20
Data Analysis | Page: 237/296 | Jobs: 20
Data Analysis | Page: 238/296 | Jobs: 20
Data Analysis | Page: 239/296 | Jobs: 20
Data Analysis | Page: 240/296 | Jobs: 20
Data Analysis | Page: 241/296 | Jobs: 20
Data Analysis | Page: 242/296 | Jobs: 20
Data Analysis | Page: 243/296 | Jobs: 20
Data Analysis | Page: 244/296 | Jobs: 20
Data Analysis | Page: 245/296 | Jobs: 20
Data Analysis | Page: 246/296 | Jobs: 20
Data Analysis | Page: 247/296 | Jobs: 20
Data Analysis | Page: 248/296 | Jobs: 20
Data Analysis | Page: 249/296 | Jobs: 20
Data Analysis | Page: 250/296 | Jobs: 20
Data Analysis | Page: 251/296 | Jobs: 20
Data Analysis | Page: 252/296 | Jobs: 20
Data Analysis | Page: 253/296 | Jobs: 20
Data Analysis | Page: 254/296 | Jobs: 20
Data Analysis | Page: 255/296 | Jobs: 20
Data Analysis | Page: 256/296 | Jobs: 20
Data Analysis | Page: 257/296 | Jobs: 20
Data Analysis | Page: 258/296 | Jobs: 20
Data Analysis | Page: 259/296 | Jobs: 20
Data Analysis | Page: 260/296 | Jobs: 20
Data Analysis | Page: 261/296 | Jobs: 20
Data Analysis | Page: 262/296 | Jobs: 20
Data Analysis | Page: 263/296 | Jobs: 20
Data Analysis | Page: 264/296 | Jobs: 20
Data Analysis | Page: 265/296 | Jobs: 20
Data Analysis | Page: 266/296 | Jobs: 20
Data Analysis | Page: 267/296 | Jobs: 20
Data Analysis | Page: 268/296 | Jobs: 20
Data Analysis | Page: 269/296 | Jobs: 19
Data Analysis | Page: 270/296 | Jobs: 0
Data Analysis | Page: 271/296 | Jobs: 0
Data Analysis | Page: 272/296 | Jobs: 0
Data Analysis | Page: 273/296 | Jobs: 0
Data Analysis | Page: 274/296 | Jobs: 0
Data Analysis | Page: 275/296 | Jobs: 0
Data Analysis | Page: 276/296 | Jobs: 0
Data Analysis | Page: 277/296 | Jobs: 0
Data Analysis | Page: 278/296 | Jobs: 0
Data Analysis | Page: 279/296 | Jobs: 0
Data Analysis | Page: 280/296 | Jobs: 0
Data Analysis | Page: 281/296 | Jobs: 0
Data Analysis | Page: 282/296 | Jobs: 0
Data Analysis | Page: 283/296 | Jobs: 0
Data Analysis | Page: 284/296 | Jobs: 0
Data Analysis | Page: 285/296 | Jobs: 0
Data Analysis | Page: 286/296 | Jobs: 0
Data Analysis | Page: 287/296 | Jobs: 0
Data Analysis | Page: 288/296 | Jobs: 0
Data Analysis | Page: 289/296 | Jobs: 0
Data Analysis | Page: 290/296 | Jobs: 0
Data Analysis | Page: 291/296 | Jobs: 0
Data Analysis | Page: 292/296 | Jobs: 0
Data Analysis | Page: 293/296 | Jobs: 0
Data Analysis | Page: 294/296 | Jobs: 0
Data Analysis | Page: 295/296 | Jobs: 0
Data Analysis | Page: 296/296 | Jobs: 0

========== Data Science | 131 Pages ==========

Data Science | Page: 1/131 | Jobs: 20
Data Science | Page: 2/131 | Jobs: 20
Data Science | Page: 3/131 | Jobs: 20
Data Science | Page: 4/131 | Jobs: 20
Data Science | Page: 5/131 | Jobs: 20
Data Science | Page: 6/131 | Jobs: 20
Data Science | Page: 7/131 | Jobs: 20
Data Science | Page: 8/131 | Jobs: 20
Data Science | Page: 9/131 | Jobs: 20
Data Science | Page: 10/131 | Jobs: 20
Data Science | Page: 11/131 | Jobs: 20
Data Science | Page: 12/131 | Jobs: 20
Data Science | Page: 13/131 | Jobs: 20
Data Science | Page: 14/131 | Jobs: 20
Data Science | Page: 15/131 | Jobs: 20
Data Science | Page: 16/131 | Jobs: 20
Data Science | Page: 17/131 | Jobs: 20
Data Science | Page: 18/131 | Jobs: 20
Data Science | Page: 19/131 | Jobs: 20
Data Science | Page: 20/131 | Jobs: 20
Data Science | Page: 21/131 | Jobs: 20
Data Science | Page: 22/131 | Jobs: 20
Data Science | Page: 23/131 | Jobs: 20
Data Science | Page: 24/131 | Jobs: 20
Data Science | Page: 25/131 | Jobs: 20
Data Science | Page: 26/131 | Jobs: 20
Data Science | Page: 27/131 | Jobs: 20
Data Science | Page: 28/131 | Jobs: 20
Data Science | Page: 29/131 | Jobs: 20
Data Science | Page: 30/131 | Jobs: 20
Data Science | Page: 31/131 | Jobs: 20
Data Science | Page: 32/131 | Jobs: 20
Data Science | Page: 33/131 | Jobs: 20
Data Science | Page: 34/131 | Jobs: 20
Data Science | Page: 35/131 | Jobs: 20
Data Science | Page: 36/131 | Jobs: 20
Data Science | Page: 37/131 | Jobs: 20
Data Science | Page: 38/131 | Jobs: 20
Data Science | Page: 39/131 | Jobs: 20
Data Science | Page: 40/131 | Jobs: 20
Data Science | Page: 41/131 | Jobs: 20
Data Science | Page: 42/131 | Jobs: 20
Data Science | Page: 43/131 | Jobs: 20
Data Science | Page: 44/131 | Jobs: 20
Data Science | Page: 45/131 | Jobs: 20
Data Science | Page: 46/131 | Jobs: 20
Data Science | Page: 47/131 | Jobs: 20
Data Science | Page: 48/131 | Jobs: 20
Data Science | Page: 49/131 | Jobs: 20
Data Science | Page: 50/131 | Jobs: 20
Data Science | Page: 51/131 | Jobs: 20
Data Science | Page: 52/131 | Jobs: 20
Data Science | Page: 53/131 | Jobs: 20
Data Science | Page: 54/131 | Jobs: 20
Data Science | Page: 55/131 | Jobs: 20
Data Science | Page: 56/131 | Jobs: 20
Data Science | Page: 57/131 | Jobs: 20
Data Science | Page: 58/131 | Jobs: 20
Data Science | Page: 59/131 | Jobs: 20
Data Science | Page: 60/131 | Jobs: 20
Data Science | Page: 61/131 | Jobs: 20
Data Science | Page: 62/131 | Jobs: 20
Data Science | Page: 63/131 | Jobs: 20
Data Science | Page: 64/131 | Jobs: 20
Data Science | Page: 65/131 | Jobs: 20
Data Science | Page: 66/131 | Jobs: 20
Data Science | Page: 67/131 | Jobs: 20
Data Science | Page: 68/131 | Jobs: 20
Data Science | Page: 69/131 | Jobs: 20
Data Science | Page: 70/131 | Jobs: 20
Data Science | Page: 71/131 | Jobs: 20
Data Science | Page: 72/131 | Jobs: 20
Data Science | Page: 73/131 | Jobs: 20
Data Science | Page: 74/131 | Jobs: 20
Data Science | Page: 75/131 | Jobs: 20
Data Science | Page: 76/131 | Jobs: 20
Data Science | Page: 77/131 | Jobs: 20
Data Science | Page: 78/131 | Jobs: 20
Data Science | Page: 79/131 | Jobs: 20
Data Science | Page: 80/131 | Jobs: 20
Data Science | Page: 81/131 | Jobs: 20
Data Science | Page: 82/131 | Jobs: 20
Data Science | Page: 83/131 | Jobs: 20
Data Science | Page: 84/131 | Jobs: 20
Data Science | Page: 85/131 | Jobs: 20
Data Science | Page: 86/131 | Jobs: 20
Data Science | Page: 87/131 | Jobs: 20
Data Science | Page: 88/131 | Jobs: 20
Data Science | Page: 89/131 | Jobs: 20
Data Science | Page: 90/131 | Jobs: 20
Data Science | Page: 91/131 | Jobs: 20
Data Science | Page: 92/131 | Jobs: 20
Data Science | Page: 93/131 | Jobs: 20
Data Science | Page: 94/131 | Jobs: 20
Data Science | Page: 95/131 | Jobs: 20
Data Science | Page: 96/131 | Jobs: 20
Data Science | Page: 97/131 | Jobs: 20
Data Science | Page: 98/131 | Jobs: 20
Data Science | Page: 99/131 | Jobs: 20
Data Science | Page: 100/131 | Jobs: 20
Data Science | Page: 101/131 | Jobs: 20
Data Science | Page: 102/131 | Jobs: 20
Data Science | Page: 103/131 | Jobs: 20
Data Science | Page: 104/131 | Jobs: 20
Data Science | Page: 105/131 | Jobs: 20
Data Science | Page: 106/131 | Jobs: 20
Data Science | Page: 107/131 | Jobs: 20
Data Science | Page: 108/131 | Jobs: 20
Data Science | Page: 109/131 | Jobs: 20
Data Science | Page: 110/131 | Jobs: 20
Data Science | Page: 111/131 | Jobs: 20
Data Science | Page: 112/131 | Jobs: 20
Data Science | Page: 113/131 | Jobs: 20
Data Science | Page: 114/131 | Jobs: 20
Data Science | Page: 115/131 | Jobs: 20
Data Science | Page: 116/131 | Jobs: 20
Data Science | Page: 117/131 | Jobs: 20
Data Science | Page: 118/131 | Jobs: 20
Data Science | Page: 119/131 | Jobs: 20
Data Science | Page: 120/131 | Jobs: 20
Data Science | Page: 121/131 | Jobs: 20
Data Science | Page: 122/131 | Jobs: 20
Data Science | Page: 123/131 | Jobs: 20
Data Science | Page: 124/131 | Jobs: 20
Data Science | Page: 125/131 | Jobs: 20
Data Science | Page: 126/131 | Jobs: 20
Data Science | Page: 127/131 | Jobs: 20
Data Science | Page: 128/131 | Jobs: 20
Data Science | Page: 129/131 | Jobs: 20
Data Science | Page: 130/131 | Jobs: 20
Data Science | Page: 131/131 | Jobs: 20

========== Data Engineering | 231 Pages ==========

Data Engineering | Page: 1/231 | Jobs: 20
Data Engineering | Page: 2/231 | Jobs: 20
Data Engineering | Page: 3/231 | Jobs: 20
Data Engineering | Page: 4/231 | Jobs: 20
Data Engineering | Page: 5/231 | Jobs: 20
Data Engineering | Page: 6/231 | Jobs: 20
Data Engineering | Page: 7/231 | Jobs: 20
Data Engineering | Page: 20/231 | Jobs: 20
Data Engineering | Page: 21/231 | Jobs: 20
Data Engineering | Page: 22/231 | Jobs: 20
Data Engineering | Page: 23/231 | Jobs: 20
Data Engineering | Page: 24/231 | Jobs: 20
Data Engineering | Page: 25/231 | Jobs: 20
Data Engineering | Page: 26/231 | Jobs: 20
Data Engineering | Page: 27/231 | Jobs: 20
Data Engineering | Page: 28/231 | Jobs: 20
Data Engineering | Page: 29/231 | Jobs: 20
Data Engineering | Page: 30/231 | Jobs: 20
Data Engineering | Page: 31/231 | Jobs: 20
Data Engineering | Page: 32/231 | Jobs: 20
Data Engineering | Page: 33/231 | Jobs: 20
Data Engineering | Page: 34/231 | Jobs: 20
Data Engineering | Page: 35/231 | Jobs: 20
Data Engineering | Page: 36/231 | Jobs: 20
Data Engineering | Page: 37/231 | Jobs: 20
Data Engineering | Page: 38/231 | Jobs: 20
Data Engineering | Page: 39/231 | Jobs: 20
Data Engineering | Page: 40/231 | Jobs: 20
Data Engineering | Page: 41/231 | Jobs: 20
Data Engineering | Page: 42/231 | Jobs: 20
Data Engineering | Page: 43/231 | Jobs: 20
Data Engineering | Page: 44/231 | Jobs: 20
Data Engineering | Page: 45/231 | Jobs: 20
Data Engineering | Page: 46/231 | Jobs: 20
Data Engineering | Page: 47/231 | Jobs: 20
Data Engineering | Page: 48/231 | Jobs: 20
Data Engineering | Page: 49/231 | Jobs: 20
Data Engineering | Page: 50/231 | Jobs: 20
Data Engineering | Page: 51/231 | Jobs: 20
Data Engineering | Page: 52/231 | Jobs: 20
Data Engineering | Page: 53/231 | Jobs: 20
Data Engineering | Page: 54/231 | Jobs: 20
Data Engineering | Page: 55/231 | Jobs: 20
Data Engineering | Page: 56/231 | Jobs: 20
Data Engineering | Page: 57/231 | Jobs: 20
Data Engineering | Page: 58/231 | Jobs: 20
Data Engineering | Page: 59/231 | Jobs: 20
Data Engineering | Page: 60/231 | Jobs: 20
Data Engineering | Page: 61/231 | Jobs: 20
Data Engineering | Page: 62/231 | Jobs: 20
Data Engineering | Page: 63/231 | Jobs: 20
Data Engineering | Page: 64/231 | Jobs: 20
Data Engineering | Page: 65/231 | Jobs: 20
Data Engineering | Page: 66/231 | Jobs: 20
Data Engineering | Page: 67/231 | Jobs: 20
Data Engineering | Page: 68/231 | Jobs: 20
Data Engineering | Page: 69/231 | Jobs: 20
Data Engineering | Page: 70/231 | Jobs: 20
Data Engineering | Page: 71/231 | Jobs: 20
Data Engineering | Page: 72/231 | Jobs: 20
Data Engineering | Page: 73/231 | Jobs: 20
Data Engineering | Page: 74/231 | Jobs: 20
Data Engineering | Page: 75/231 | Jobs: 20

,Title,Type_Location,Date,Category,Data_Category,Company_name,Type_Work,Source,Location,Job_Link,Page
0,Statistics And Data Analysis Trainer,Hybrid - Egypt - Cairo,13 August 2026,Education & Training,Data Analysis,E3mel business Academy,Full Time,LinkedIn,Egypt - Cairo,https://egypt.tanqeeb.com/jobs-in-egypt/all/jo...,1
1,Data Analysis Specialist,On-site - Egypt - Cairo,26 July 2026,Information Technology,Data Analysis,j&t express,Full Time,LinkedIn,Egypt - Cairo,https://egypt.tanqeeb.com/jobs-in-egypt/all/jo...,1
2,Data Analysis and Revenue Growth Specialist,On-site - Egypt - Cairo,5 August 2026,"Accounting, Finance & Banking",Data Analysis,geidea,Full Time,LinkedIn,Egypt - Cairo,https://egypt.tanqeeb.com/jobs-in-egypt/all/jo...,1
3,Senior Data Engineer - AI Business Analysis,On-site - Egypt - Cairo,7 July 2026,"Logistics, Supply Chain & Procurement",Data Analysis,NOK Human Capital,Full Time,LinkedIn,Egypt - Cairo,https://egypt.tanqeeb.com/jobs-in-egypt/all/jo...,1
4,Content Marketing & Data Analysis Assistant,On-site - Egypt - Cairo,17 July 2026,Sales,Data Analysis,Wecrin Inc.,Internship,Naukri Gulf,Egypt - Cairo,https://egypt.tanqeeb.com/jobs-in-egypt/all/jo...,1

In [7]:
df["Type_Location"] = df['Type_Location'].str.split().str[0]

In [11]:
df

,Title,Type_Location,Date,Category,Data_Category,Company_name,Type_Work,Source,Location,Job_Link,Page
0,Statistics And Data Analysis Trainer,Hybrid,13 August 2026,Education & Training,Data Analysis,E3mel business Academy,Full Time,LinkedIn,Egypt - Cairo,https://egypt.tanqeeb.com/jobs-in-egypt/all/jo...,1
1,Data Analysis Specialist,On-site,26 July 2026,Information Technology,Data Analysis,j&t express,Full Time,LinkedIn,Egypt - Cairo,https://egypt.tanqeeb.com/jobs-in-egypt/all/jo...,1
2,Data Analysis and Revenue Growth Specialist,On-site,5 August 2026,"Accounting, Finance & Banking",Data Analysis,geidea,Full Time,LinkedIn,Egypt - Cairo,https://egypt.tanqeeb.com/jobs-in-egypt/all/jo...,1
3,Senior Data Engineer - AI Business Analysis,On-site,7 July 2026,"Logistics, Supply Chain & Procurement",Data Analysis,NOK Human Capital,Full Time,LinkedIn,Egypt - Cairo,https://egypt.tanqeeb.com/jobs-in-egypt/all/jo...,1
4,Content Marketing & Data Analysis Assistant,On-site,17 July 2026,Sales,Data Analysis,Wecrin Inc.,Internship,Naukri Gulf,Egypt - Cairo,https://egypt.tanqeeb.com/jobs-in-egypt/all/jo...,1
...,...,...,...,...,...,...,...,...,...,...,...
16964,Chatbot Developer,Remote,5 July 2026,Information Technology,Artificial Intelligence,Mindrift,Full Time,Bayt,Egypt - Cairo,https://egypt.tanqeeb.com/jobs-in-egypt/all/jo...,30
16965,Senior JavaScript Developer (Short term),Remote,3 September 2026,NaN,Artificial Intelligence,Intetics,Full Time,Bayt,Egypt - Cairo,https://egypt.tanqeeb.com/jobs-in-egypt/all/jo...,30
16966,AI Engineer / AI Automation Specialist,Remote,28 August 2026,Telecom & Technology,Artificial Intelligence,Pavago,Full Time,Bayt,Egypt - Cairo,https://egypt.tanqeeb.com/jobs-in-egypt/all/jo...,30
16967,AI Engineering Manager,On-site,17 July 2026,Information Technology,Artificial Intelligence,Unifonic,Full Time,Bayt,Egypt - Cairo,https://egypt.tanqeeb.com/jobs-in-egypt/all/jo...,30
16968,Executive Assistant to the CEO,On-site,20 August 2026,Administration,Artificial Intelligence,إياس للاستشارات والحلول المؤسسية,Full Time,Tanqeeb.com,Egypt - Cairo,https://egypt.tanqeeb.com/jobs-in-egypt/all/jo...,30

In [12]:
df.isna().sum()

Title              0
Type_Location      0
Date               0
Category         728
Data_Category      0
Company_name       0
Type_Work          0
Source             0
Location           0
Job_Link           0
Page               0
dtype: int64

In [16]:
df.to_csv(r'D:\Tanqeeb_Jobs.csv', index=False, encoding='utf-8-sig')